import{a as b,S as v,i as a}from"./assets/vendor-BNibzuFn.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&s(l)}).observe(document,{childList:!0,subtree:!0});function t(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(r){if(r.ep)return;r.ep=!0;const n=t(r);fetch(r.href,n)}})();const P="51535484-ce6dacd6a97960c9e0e55a6bc",S="https://pixabay.com/api/",q=15;async function m(e,o=1){const t={key:P,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:q};try{return(await b.get(S,{params:t})).data}catch(s){throw new Error("Failed to fetch images: "+s.message)}}const h=document.querySelector(".gallery");let $=new v(".gallery a");function y(){return document.querySelector(".loader")}function g(){const e=y();e&&e.classList.remove("hidden")}function p(){const e=y();e&&e.classList.add("hidden")}function R(){h.innerHTML=""}function L(e){const o=e.map(t=>`
      <li class="gallery-item">
        <a href="${t.largeImageURL}">
          <img src="${t.webformatURL}" alt="${t.tags}" />
        </a>
        <div class="info">
          <p>Likes: ${t.likes}</p>
          <p>Views: ${t.views}</p>
          <p>Comments: ${t.comments}</p>
          <p>Downloads: ${t.downloads}</p>
        </div>
      </li>`).join("");h.insertAdjacentHTML("beforeend",o),$.refresh()}function E(){const e=document.querySelector(".load-more");e&&e.classList.remove("hidden")}function c(){const e=document.querySelector(".load-more");e&&e.classList.add("hidden")}const f=document.querySelector(".form"),w=40;let i=1,d="",u=0;f.addEventListener("submit",async e=>{e.preventDefault();const o=f.querySelector('input[name="search-text"]');if(!o){a.error({title:"Error",message:"Search input not found in the form."});return}const t=o.value.trim();if(!t){a.warning({title:"Warning",message:"Please enter a search query!"});return}d=t,i=1,R(),c(),g();try{const s=await m(d,i);if(u=s.totalHits,!s.hits||s.hits.length===0){a.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"});return}L(s.hits),u>w?E():(c(),a.info({title:"End of Collection",message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{p()}});document.addEventListener("click",async e=>{if(e.target.classList.contains("load-more")){i++,c(),g();try{const o=await m(d,i);L(o.hits);const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),i*w>=u?(c(),a.info({title:"End of Collection",message:"We're sorry, but you've reached the end of search results."})):E()}catch{a.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{p()}}});
//# sourceMappingURL=index.js.map
